# Generated by Django 3.2.25 on 2024-06-03 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='users/user1.png', null=True, upload_to='users'),
        ),
    ]
