# Generated by Django 3.2.25 on 2024-04-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50), unique=True),
        ),
    ]
