# Generated by Django 3.2.25 on 2024-06-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240603_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_cards',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='home.Card'),
        ),
    ]
