# Generated by Django 3.2.25 on 2024-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
